apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/ecr-operator-serving-cert
  name: ecr-operator-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: ecr-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-pod
  failurePolicy: Fail
  name: pod.aws.zakariaamine.com
  objectSelector:
    matchExpressions:
    - key: control-plane
      operator: NotIn
      values:
      - controller-manager
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: NoneOnDryRun
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: ecr-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-secret-delete
  failurePolicy: Fail
  name: secret.aws.zakariaamine.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - secrets
  sideEffects: NoneOnDryRun
