# permissions for end users to view awsecrcredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsecrcredential-viewer-role
rules:
- apiGroups:
  - aws.zakariaamine.com
  resources:
  - awsecrcredentials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.zakariaamine.com
  resources:
  - awsecrcredentials/status
  verbs:
  - get
