# permissions for end users to edit awsecrcredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsecrcredential-editor-role
rules:
- apiGroups:
  - aws.zakariaamine.com
  resources:
  - awsecrcredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.zakariaamine.com
  resources:
  - awsecrcredentials/status
  verbs:
  - get
